# Generated by Django 5.0.6 on 2024-06-09 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian_app', '0005_boardgame'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateTimeField(auto_now_add=True)),
                ('date_retour', models.DateTimeField(blank=True, null=True)),
                ('cd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='librarian_app.cd')),
                ('dvd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='librarian_app.dvd')),
                ('emprunteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarian_app.emprunteur')),
                ('livre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='librarian_app.livre')),
            ],
        ),
    ]
